apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "zfs-provisioner.fullname" . }}
  labels:
    {{- include "zfs-provisioner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zfs-provisioner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zfs-provisioner.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zfs-provisioner.serviceAccountName" . }}
      containers:
        - name: provisioner
          securityContext:
            privileged: true
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZFS_PROVISIONER_INSTANCE
              value: {{ .Values.provisioner.instance }}
            - name: ZFS_PARENT_DATASET
              value: {{ .Values.provisioner.parentDataset }}
            - name: ZFS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- with .Values.env }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: dev-zfs
              mountPath: /dev/zfs
            - name: dataset
              mountPath: {{ .Values.provisioner.parentMountPath }}
              mountPropagation: Bidirectional
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: dev-zfs
          hostPath:
            path: /dev/zfs
        - name: dataset
          hostPath:
            path: {{ .Values.provisioner.parentMountPath }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.provisioner.nodeName }}
