{{- if .Values.storageClass.create -}}
{{- range .Values.storageClass.classes }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
  labels:
    {{- include "zfs-provisioner.labels" $ | nindent 4 }}
{{- with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
provisioner: {{ $.Values.provisioner.instance }}
reclaimPolicy: {{ .policy | default "Delete" }}
parameters:
  {{- if kindIs "bool" .reserveSpace }}
  reserveSpace: {{ quote .reserveSpace }}
  {{- end }}
{{- end }}
{{- end }}
